services:
  fastapi-app:
    build: .
    container_name: apilare_fastapi
    ports:
      - "2006:2006"
    volumes:
      - ./db.json:/app/db.json
    env_file:
      - .env
    restart: unless-stopped
